linters-settings:
  goimports:
    local-prefixes: github.com/exfly/vulcan
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - exportloopref
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

    - sqlclosecheck

    # don't enable:
    - asciicheck
    - godox
    - goerr113
    - nestif
    - prealloc
    - testpackage
#    - wsl
#    - gochecknoglobals
#    - gocognit
#    - godot
#    - stylecheck

    # not exists,archived
    #- golint
    #- interfacer
    #- maligned
    #- scopelint
    # - exhaustive
    # - noctx

run:
  skip-dirs:
    - api/
    - proto/
