// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/exfly/vulcan/internel/config"
	"github.com/exfly/vulcan/internel/database"
	"github.com/exfly/vulcan/internel/user/repo"
	"github.com/exfly/vulcan/internel/user/rpc"
)

import (
	_ "github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/jackc/pgx/v5/stdlib"
)

// Injectors from wire.go:

func NewApp(path config.Path) (*App, error) {
	configConfig, err := config.LoadConfig(path)
	if err != nil {
		return nil, err
	}
	db, err := database.New(configConfig)
	if err != nil {
		return nil, err
	}
	store := user.NewStore(db)
	server, err := rpc.New(configConfig, store)
	if err != nil {
		return nil, err
	}
	app, err := newApp(configConfig, server)
	if err != nil {
		return nil, err
	}
	return app, nil
}
